import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import Header from "./components/header";
import { UserButton } from "@clerk/nextjs";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-[13vh] flex justify-between items-center">
          <div className="w-1/3 h-full">

          </div>

          <div className="w-1/3 h-full">
            <Header />
          </div>

          <div className="w-1/3 h-full flex justify-end items-start pr-3 pt-3">
            <UserButton/>
          </div>
        </div>

        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
